export default [
	{ Name: 'No Category', Value: '' },
	{ Name: 'Interior', Value: 'interior' },
	{ Name: 'Babyrooms', Value: 'babyrooms' },
	{ Name: 'Bedlinnen', Value: 'bedlinnen' },
	{ Name: 'Kids rooms', Value: 'kidsrooms' },
	{ Name: 'Accessories', Value: 'accessories' },
	{ Name: 'Clothing', Value: 'clothing' },
	{ Name: 'Babies', Value: 'babies' },
	{ Name: 'Girls', Value: 'girls' },
	{ Name: 'Boys', Value: 'boys' },
	{ Name: 'Safety', Value: 'safety' },
	{ Name: 'Chairs', Value: 'chairs' },
	{ Name: 'Playpens', Value: 'playpens' },
	{ Name: 'Babyphones', Value: 'babyphones' },
	{ Name: 'On the move', Value: 'on the move' },
	{ Name: 'Car Seats', Value: 'car seats' },
	{ Name: 'Buggies', Value: 'buggies' },
	{ Name: 'Strollers', Value: 'strollers' },
	{ Name: 'Toys', Value: 'Toys' },
	{ Name: 'Games', Value: 'Games' },
	{ Name: 'Construction', Value: 'Construction' },
	{ Name: 'Hobbies', Value: 'Hobbies' },
	{ Name: 'Outdoors', Value: 'Outdoors' },
	{ Name: 'Lego', Value: 'Lego' },
	{ Name: 'Playmobil', Value: 'Playmobil' },
	{ Name: 'Disney', Value: 'Disney' },
	{ Name: 'Star Wars', Value: 'Star Wars' },
	{ Name: 'Fortnite', Value: 'Fortnite' },
	{ Name: 'Pokemon', Value: 'Pokemon' }
];
